# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogWindow(object):
    def setupUi(self, DialogWindow):
        DialogWindow.setObjectName("DialogWindow")
        DialogWindow.resize(500, 190)
        DialogWindow.setMinimumSize(QtCore.QSize(500, 190))
        DialogWindow.setMaximumSize(QtCore.QSize(500, 190))
        DialogWindow.setStyleSheet("QWidget{\n"
                                   "background-color:qlineargradient(spread:pad, x1:0.025, y1:0.385909, x2:0.99, y2:0.374364, stop:0 rgba(255, 18, 3, 255), stop:1 rgba(76, 16, 255, 255))\n"
                                   "}")
        self.Name_Label = QtWidgets.QLabel(DialogWindow)
        self.Name_Label.setGeometry(QtCore.QRect(30, 30, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(16)
        self.Name_Label.setFont(font)
        self.Name_Label.setStyleSheet("QLabel{\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "background-color:rgb(255, 170, 255)rgb(85, 0, 127)\n"
                                      "}")
        self.Name_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Name_Label.setObjectName("Name_Label")
        self.Name_Input = QtWidgets.QLineEdit(DialogWindow)
        self.Name_Input.setGeometry(QtCore.QRect(50, 70, 391, 28))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(12)
        self.Name_Input.setFont(font)
        self.Name_Input.setStyleSheet("QLineEdit{\n"
                                      "background-color: rgb(203, 203, 203);\n"
                                      "border-radius: 10px;\n"
                                      "}")
        self.Name_Input.setObjectName("Name_Input")
        self.SaveButton = QtWidgets.QPushButton(DialogWindow)
        self.SaveButton.setGeometry(QtCore.QRect(180, 110, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.SaveButton.sizePolicy().hasHeightForWidth())
        self.SaveButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.SaveButton.setFont(font)
        self.SaveButton.setStyleSheet("QPushButton{\n"
                                      "background-color:rgb(203, 203, 203);\n"
                                      "border:none;\n"
                                      "color:rgb(0, 0, 0);\n"
                                      "padding-top:5px;\n"
                                      "text-align: center;\n"
                                      "border-radius:15px\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(158, 158, 158);\n"
                                      "}\n"
                                      "QPushButton:pressed{\n"
                                      "background-color:rgb(158, 158, 158);\n"
                                      "}")
        self.SaveButton.setObjectName("SaveButton")

        self.retranslateUi(DialogWindow)
        QtCore.QMetaObject.connectSlotsByName(DialogWindow)

    def retranslateUi(self, DialogWindow):
        DialogWindow.setWindowIcon(QtGui.QIcon('resources/icon.png'))
        _translate = QtCore.QCoreApplication.translate
        DialogWindow.setWindowTitle(_translate(
            "DialogWindow", "eMag Price Tracker"))
        self.Name_Label.setText(_translate("DialogWindow", "Name the preset"))
        self.SaveButton.setText(_translate("DialogWindow", "Save preset"))
