# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(750, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(1000, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        self.MainFrame.setGeometry(QtCore.QRect(0, 0, 1000, 600))
        self.MainFrame.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.MainFrame.setStyleSheet("QFrame{\n"
                                     "background-color:qlineargradient(spread:pad, x1:0.025, y1:0.385909, x2:0.99, y2:0.374364, stop:0 rgba(255, 18, 3, 255), stop:1 rgba(76, 16, 255, 255));\n"
                                     "border-radius: 10px;\n"
                                     "}")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.logo = QtWidgets.QLabel(self.MainFrame)
        self.logo.setGeometry(QtCore.QRect(0, 100, 1000, 201))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        self.logo.setFont(font)
        self.logo.setStyleSheet("QLabel{\n"
                                "qlineargradient(spread:pad, x1:0.025, y1:0.385909, x2:0.99, y2:0.374364, stop:0 rgba(255, 18, 3, 255), stop:1 rgba(76, 16, 255, 255))\n"
                                "}")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("resources/logo2.png"))
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setWordWrap(False)
        self.logo.setIndent(0)
        self.logo.setObjectName("logo")
        self.emailLabel = QtWidgets.QLabel(self.MainFrame)
        self.emailLabel.setGeometry(QtCore.QRect(10, 260, 1000, 51))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(18)
        self.emailLabel.setFont(font)
        self.emailLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.emailLabel.setObjectName("emailLabel")
        self.emailText = QtWidgets.QLineEdit(self.MainFrame)
        self.emailText.setGeometry(QtCore.QRect(210, 303, 571, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.emailText.sizePolicy().hasHeightForWidth())
        self.emailText.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(12)
        self.emailText.setFont(font)
        self.emailText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.emailText.setStyleSheet("QLineEdit{\n"
                                     "background-color:rgb(207, 207, 207);\n"
                                     "color:rgb(0, 0, 0);\n"
                                     "border-radius: 10px;\n"
                                     "}")
        self.emailText.setText("")
        self.emailText.setAlignment(QtCore.Qt.AlignCenter)
        self.emailText.setObjectName("emailText")
        self.creditLabel = QtWidgets.QLabel(self.MainFrame)
        self.creditLabel.setGeometry(QtCore.QRect(10, 555, 981, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.creditLabel.setFont(font)
        self.creditLabel.setAlignment(
            QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.creditLabel.setObjectName("creditLabel")
        self.helpButton = QtWidgets.QToolButton(self.MainFrame)
        self.helpButton.setGeometry(QtCore.QRect(8, 570, 23, 23))
        self.helpButton.setStyleSheet("QToolButton{\n"
                                      "background-color:rgb(203, 203, 203);\n"
                                      "border:none;\n"
                                      "color:rgb(0, 0, 0);\n"
                                      "padding-top:5px;\n"
                                      "border-radius:10px\n"
                                      "}\n"
                                      "QToolButton:hover{\n"
                                      "background-color:rgb(158, 158, 158);\n"
                                      "}\n"
                                      "QToolButton:pressed{\n"
                                      "background-color:rgb(158, 158, 158);\n"
                                      "}")
        self.helpButton.setText("")
        self.helpButton.setObjectName("helpButton")
        self.AccesButton = QtWidgets.QPushButton(self.MainFrame)
        self.AccesButton.setGeometry(QtCore.QRect(410, 340, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.AccesButton.setFont(font)
        self.AccesButton.setStyleSheet("QPushButton{\n"
                                       "background-color:rgb(203, 203, 203);\n"
                                       "border:none;\n"
                                       "color:rgb(0, 0, 0);\n"
                                       "padding-top:5px;\n"
                                       "border-radius:15px\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "background-color:rgb(158, 158, 158);\n"
                                       "}\n"
                                       "QPushButton:pressed{\n"
                                       "background-color:rgb(158, 158, 158);\n"
                                       "}")
        self.AccesButton.setObjectName("AccesButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowIcon(QtGui.QIcon('resources/icon.png'))
        MainWindow.setWindowTitle(_translate(
            "eMag Price Tracker", "eMag Price Tracker"))
        self.emailLabel.setText(_translate(
            "MainWindow", "<strong> Enter your email and start tracking </strong>"))
        self.emailText.setPlaceholderText(
            _translate("MainWindow", "enter your email"))
        self.creditLabel.setText(_translate(
            "MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:7pt;\">Created by Robert Dragoi</span></p></body></html>"))
        self.AccesButton.setText(_translate("MainWindow", "Track prices"))
