# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectWindow(object):
    def setupUi(self, SelectWindow):
        SelectWindow.setObjectName("SelectWindow")
        SelectWindow.resize(600, 350)
        SelectWindow.setMinimumSize(QtCore.QSize(600, 350))
        SelectWindow.setMaximumSize(QtCore.QSize(600, 350))
        SelectWindow.setStyleSheet("QWidget{\n"
                                   "background-color:qlineargradient(spread:pad, x1:0.025, y1:0.385909, x2:0.99, y2:0.374364, stop:0 rgba(255, 18, 3, 255), stop:1 rgba(76, 16, 255, 255))\n"
                                   "}")
        self.verticalLayoutWidget = QtWidgets.QWidget(SelectWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 10, 581, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.List = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.List.setStyleSheet("QListWidget{\n"
                                "background-color:rgb(203, 203, 203);\n"
                                "\n"
                                "}")
        self.List.setObjectName("List")
        self.verticalLayout.addWidget(self.List)
        self.Button = QtWidgets.QPushButton(SelectWindow)
        self.Button.setGeometry(QtCore.QRect(240, 300, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.Button.sizePolicy().hasHeightForWidth())
        self.Button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.Button.setFont(font)
        self.Button.setStyleSheet("QPushButton{\n"
                                  "background-color:rgb(203, 203, 203);\n"
                                  "border:none;\n"
                                  "color:rgb(0, 0, 0);\n"
                                  "padding-top:5px;\n"
                                  "text-align: center;\n"
                                  "border-radius:15px\n"
                                  "}\n"
                                  "QPushButton:hover{\n"
                                  "background-color:rgb(158, 158, 158);\n"
                                  "}\n"
                                  "QPushButton:pressed{\n"
                                  "background-color:rgb(158, 158, 158);\n"
                                  "}")
        self.Button.setObjectName("Button")

        self.retranslateUi(SelectWindow)
        QtCore.QMetaObject.connectSlotsByName(SelectWindow)

    def retranslateUi(self, SelectWindow):
        SelectWindow.setWindowIcon(QtGui.QIcon('resources/icon.png'))
        _translate = QtCore.QCoreApplication.translate
        SelectWindow.setWindowTitle(_translate(
            "SelectWindow", "eMag Price Tracker"))
        self.Button.setText(_translate("SelectWindow", "text"))
