# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TrackerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrackerWindow(object):
    def setupUi(self, TrackerWindow):
        TrackerWindow.setObjectName("TrackerWindow")
        TrackerWindow.resize(1000, 800)
        TrackerWindow.setMinimumSize(QtCore.QSize(750, 500))
        TrackerWindow.setMaximumSize(QtCore.QSize(1000, 800))
        self.centralwidget = QtWidgets.QWidget(TrackerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        self.MainFrame.setGeometry(QtCore.QRect(0, 0, 1000, 800))
        self.MainFrame.setStyleSheet("QFrame{\n"
                                     "background-color:qlineargradient(spread:pad, x1:0.025, y1:0.385909, x2:0.99, y2:0.374364, stop:0 rgba(255, 18, 3, 255), stop:1 rgba(76, 16, 255, 255));\n"
                                     "border-radius: 10px;\n"
                                     "}")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.MainFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 981, 441))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Tracker_List = QtWidgets.QListWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Historic")
        font.setPointSize(12)
        self.Tracker_List.setFont(font)
        self.Tracker_List.setStyleSheet("QListWidget{\n"
                                        "background-color: rgb(203, 203, 203)\n"
                                        "}")
        self.Tracker_List.setObjectName("Tracker_List")
        self.verticalLayout.addWidget(self.Tracker_List)
        self.Link_Input = QtWidgets.QLineEdit(self.MainFrame)
        self.Link_Input.setGeometry(QtCore.QRect(11, 10, 981, 28))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(12)
        self.Link_Input.setFont(font)
        self.Link_Input.setStyleSheet("QLineEdit{\n"
                                      "background-color: rgb(203, 203, 203);\n"
                                      "border-radius: 10px;\n"
                                      "}")
        self.Link_Input.setObjectName("Link_Input")
        self.AddButton = QtWidgets.QPushButton(self.MainFrame)
        self.AddButton.setGeometry(QtCore.QRect(10, 50, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.AddButton.sizePolicy().hasHeightForWidth())
        self.AddButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.AddButton.setFont(font)
        self.AddButton.setStyleSheet("QPushButton{\n"
                                     "background-color:rgb(203, 203, 203);\n"
                                     "border:none;\n"
                                     "color:rgb(0, 0, 0);\n"
                                     "padding-top:5px;\n"
                                     "text-align: center;\n"
                                     "border-radius:15px\n"
                                     "}\n"
                                     "QPushButton:hover{\n"
                                     "background-color:rgb(158, 158, 158);\n"
                                     "}\n"
                                     "QPushButton:pressed{\n"
                                     "background-color:rgb(158, 158, 158);\n"
                                     "}")
        self.AddButton.setObjectName("AddButton")
        self.SaveButton = QtWidgets.QPushButton(self.MainFrame)
        self.SaveButton.setGeometry(QtCore.QRect(160, 50, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.SaveButton.sizePolicy().hasHeightForWidth())
        self.SaveButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.SaveButton.setFont(font)
        self.SaveButton.setStyleSheet("QPushButton{\n"
                                      "background-color:rgb(203, 203, 203);\n"
                                      "border:none;\n"
                                      "color:rgb(0, 0, 0);\n"
                                      "padding-top:5px;\n"
                                      "text-align: center;\n"
                                      "border-radius:15px\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(158, 158, 158);\n"
                                      "}\n"
                                      "QPushButton:pressed{\n"
                                      "background-color:rgb(158, 158, 158);\n"
                                      "}")
        self.SaveButton.setObjectName("SaveButton")
        self.LoadButton = QtWidgets.QPushButton(self.MainFrame)
        self.LoadButton.setGeometry(QtCore.QRect(310, 50, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.LoadButton.sizePolicy().hasHeightForWidth())
        self.LoadButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.LoadButton.setFont(font)
        self.LoadButton.setStyleSheet("QPushButton{\n"
                                      "background-color:rgb(203, 203, 203);\n"
                                      "border:none;\n"
                                      "color:rgb(0, 0, 0);\n"
                                      "padding-top:5px;\n"
                                      "text-align: center;\n"
                                      "border-radius:15px\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background-color:rgb(158, 158, 158);\n"
                                      "}\n"
                                      "QPushButton:pressed{\n"
                                      "background-color:rgb(158, 158, 158);\n"
                                      "}")
        self.LoadButton.setObjectName("LoadButton")
        self.Status_Label = QtWidgets.QLabel(self.MainFrame)
        self.Status_Label.setGeometry(QtCore.QRect(600, 50, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(12)
        self.Status_Label.setFont(font)
        self.Status_Label.setStyleSheet("QLabel{\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "background-color:rgb(255, 170, 255)rgb(85, 0, 127)\n"
                                        "}")
        self.Status_Label.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.Status_Label.setObjectName("Status_Label")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.MainFrame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 540, 981, 241))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Notif_List = QtWidgets.QListWidget(self.verticalLayoutWidget_2)
        self.Notif_List.setStyleSheet("QListWidget{\n"
                                      "background-color: rgb(203, 203, 203)\n"
                                      "}")
        self.Notif_List.setObjectName("Notif_List")
        self.verticalLayout_2.addWidget(self.Notif_List)
        self.DeleteButton = QtWidgets.QPushButton(self.MainFrame)
        self.DeleteButton.setGeometry(QtCore.QRect(460, 50, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.DeleteButton.sizePolicy().hasHeightForWidth())
        self.DeleteButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.DeleteButton.setFont(font)
        self.DeleteButton.setStyleSheet("QPushButton{\n"
                                        "background-color:rgb(203, 203, 203);\n"
                                        "border:none;\n"
                                        "color:rgb(0, 0, 0);\n"
                                        "padding-top:5px;\n"
                                        "text-align: center;\n"
                                        "border-radius:15px\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background-color:rgb(158, 158, 158);\n"
                                        "}\n"
                                        "QPushButton:pressed{\n"
                                        "background-color:rgb(158, 158, 158);\n"
                                        "}")
        self.DeleteButton.setObjectName("DeleteButton")
        TrackerWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TrackerWindow)
        QtCore.QMetaObject.connectSlotsByName(TrackerWindow)

    def retranslateUi(self, TrackerWindow):
        TrackerWindow.setWindowIcon(QtGui.QIcon('resources/icon.png'))
        _translate = QtCore.QCoreApplication.translate
        TrackerWindow.setWindowTitle(_translate(
            "TrackerWindow", "eMag Price Tracker"))
        self.AddButton.setText(_translate("TrackerWindow", "Add product"))
        self.SaveButton.setText(_translate("TrackerWindow", "Save preset"))
        self.LoadButton.setText(_translate("TrackerWindow", "Load preset"))
        self.Status_Label.setText(_translate(
            "TrackerWindow", "No preset loaded!"))
        self.DeleteButton.setText(_translate("TrackerWindow", "Delete preset"))
